name: Publish GitHub Pages
on: [push, workflow_dispatch, release]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          git pull

          git checkout library
          git branch -C library website
          git checkout website

          git mv README.md index.md
          git rm index.js package.json LICENSE.md
          git mv pages/*.md *.md

          git rm -r .github/*          
          echo "theme: jekyll-theme-minimal" > _config.yml
      - name: Build JSDoc classes
        uses: wibbuffey/jsdoc2md@v1.1.7
        with:
          source: ./class/*
          output: ./class.md
      - name: Build JSDoc functions
        uses: wibbuffey/jsdoc2md@v1.1.7
        with:
          source: ./utils/*
          output: ./utils.md
      - name: Push to GitHub Pages
        run: |
          git rm class/*
          git rm utils/*
          git rm .gitignore

          echo -e "\nTo begin reading the documentation:\n- [Classes](./class)\n- [Functions](./utils.md)\n- [Slope.js Guide](./guide.md)" >> index.md

          git config --global user.name "Automatic Updates"
          git config --global user.email "actions@github.com"
          git config pull.rebase false  

          git add .
          git commit -m "update pages"
          git push -f origin HEAD
