name: Publish GitHub Pages
on: [push, workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          git pull
          
          git checkout library
          git branch -C library pages
          git checkout pages

          git mv README.md index.md
          git rm index.js package.json LICENSE.md

          git rm -r .github/*          
          echo "theme: jekyll-theme-minimal" > _config.yml
      - name: Build JSDoc classes
        uses: wibbuffey/jsdoc2md@v1.1.7
        with:
          source: ./class/*
          output: ./class.md
      - name: Build JSDoc functions
        uses: wibbuffey/jsdoc2md@v1.1.7
        with:
          source: ./utils/*
          output: ./utils.md
      - name: Push to GitHub actions
        run: |
          git rm class/*
          git rm utils/*
          git rm .gitignore
          
          echo -e "\nTo begin reading the documentation:\n- [Classes](./class)\n- [Functions](./utils.md)" >> index.md
          
          git config --global user.name "Automatic Updates"
          git config --global user.email "actions@github.com"
          git config pull.rebase false  
          
          git add .
          git commit -m "update pages"
          git push -f origin HEAD
          
      - name: Push to GitHub Wiki
        run: |
          git remote add wiki https://github.com/wibbuffey/slope.wiki.git
          git mv index.md Home.md
          git mv class.md Classes.md
          git mv utils.md Functions.md
          git rm _config.yml
          
          git fetch --unshallow wiki
          git add .
          git commit -m "Update wiki"
          git push -f wiki pages:master
