name: Update GitHub Pages
on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          git pull
          
          git checkout library
          git branch -C library pages
          git checkout pages

          git mv README.md index.md
          git rm index.js package.json

          git mv class class-OLD
          git mv utils utils-OLD

          git mv .github/CONTRIBUTING.md .
          git mv .github/SECURITY.md .
          git mv .github/CODE_OF_CONDUCT.md .

          git rm .github/PULL_REQUEST_TEMPLATE.md
          git rm .github/workflows/*
          git rm .github/ISSUE_TEMPLATE/*
          
          echo "theme: jekyll-theme-minimal" > _config.yml
      - name: Build JSDoc classes
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./class-OLD
          output_dir: ./class
      - name: Build JSDoc functions
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./utils-OLD
          output_dir: ./utils
      - name: Push to GitHub actions
        run: |
          git config --global user.name "Automatic Updates"
          git config --global user.email "actions@github.com"
          git config pull.rebase false  
          
          git rm -f utils-OLD/*
          git rm -f class-OLD/*

          cd utils
          echo "# slope: Functions\n" >> index.md

          for i in *; do
            f="${filename%.*}"

            if [ ! "$i" == "index.md" ]
            then
              echo "- [$f](./$i)" >> index.md
            fi
          done

          cd ../class
          echo "# slope: Classes\n" >> index.md

          for i in *; do
            f="${filename%.*}"

            if [ ! "$i" == "index.md" ]
            then
              echo "- [$f](./$i)" >> index.md
            fi
          done

          cd ..

          git add .
          git commit -m "update pages"
          git pull
          git push origin HEAD
